global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:5000']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:5000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
